package me.ziue.license.backend;

import me.ziue.api.chat.ChatUtil;
import me.ziue.license.License;
import org.bukkit.entity.Player;

public class ServerConnector {

    public String server = License.getLicense().getConfig().getString("SERVER"); //https://hlicense.000webhostapp.com/request.php/

    public void checkLicense(String license, String plugin, Player player) {
        Server database = new Server(license, server, plugin);
        database.request();

        player.sendMessage(ChatUtil.translate("&eChecking: &f" + database.getLicense() + " &efor plugin, &f" + database.getPlugin()));

        if (database.isValid()) {
            player.sendMessage(ChatUtil.translate("§7§m------------------------------"));
            player.sendMessage(ChatUtil.translate("&9&lLicense Information:"));
            player.sendMessage(ChatUtil.translate("&7| &9Time Generated: &f" + database.getGeneratedIn()));
            player.sendMessage(ChatUtil.translate("&7| &9Generated by: &f" + database.getGeneratedBy()));
            player.sendMessage(ChatUtil.translate("&7| &9License: &f" + database.getLicense()));
            player.sendMessage(ChatUtil.translate("&7| &9Plugin: &f" + database.getPlugin()));
            player.sendMessage(ChatUtil.translate("&7| &9State: &f" + database.getReturn()));
            player.sendMessage(ChatUtil.translate("§7§m------------------------------"));
        } else {
            player.sendMessage(ChatUtil.translate("&9&lLicense Information:"));
            player.sendMessage(ChatUtil.translate("&7| &9License: &f" + database.getLicense()));
            player.sendMessage(ChatUtil.translate("&7| &9State: &f" + database.getReturn()));
        }
    }
}
