package me.ziue.license.command.impl;

import me.ziue.api.chat.ChatUtil;
import me.ziue.api.command.BaseCommand;
import me.ziue.api.command.Command;
import me.ziue.api.command.CommandArgs;
import me.ziue.license.License;
import me.ziue.license.backend.ReturnType;
import me.ziue.license.backend.Server;
import org.bukkit.entity.Player;

public class LicenseCreateCommand extends BaseCommand {

    public String server = License.getLicense().getConfig().getString("SERVER-ADD");
    public String serverdb = License.getLicense().getConfig().getString("SERVER-DB");

    @Command(name = "license.create")
    @Override
    public void onCommand(CommandArgs command) {
        Player player = command.getPlayer();
        String[] args = command.getArgs();

        if(args.length < 6) {
            player.sendMessage(ChatUtil.translate("&cUsage: /license create <discord> <plugin> <license> <createdby> <createdin> <maxips>"));
            return;
        }

        // String sql = "INSERT INTO licenses " + " (DISCORD, PLUGIN, LICENSE, `CREATED-BY`, `CREATED-IN`, `MAX-IPS`)" + " values ('" + args[2] + "', '" + args[1] + "', '" + args[0] + "', '" + args[4] + "', '" + args[5] + "', '" + args[3] + "')";

        Server database = new Server(args[0], args[1], args[2], args[3], args[4], args[5], server);
        database.authenticateDatabase(args[0], args[1], args[2], args[3], args[4], args[5], serverdb);

        player.sendMessage(ChatUtil.translate("&aLicense created."));
        player.sendMessage(ChatUtil.translate("§7§m------------------------------"));
        player.sendMessage(ChatUtil.translate("&9&lLicense Information:"));
        player.sendMessage(ChatUtil.translate("&7| &9Time Generated: &f" + database.getGeneratedIn()));
        player.sendMessage(ChatUtil.translate("&7| &9Generated by: &f" + database.getGeneratedBy()));
        player.sendMessage(ChatUtil.translate("&7| &9License: &f" + database.getLicense()));
        player.sendMessage(ChatUtil.translate("&7| &9Discord: &f" + database.getDiscord()));
        player.sendMessage(ChatUtil.translate("&7| &9Plugin: &f" + database.getPlugin()));
        player.sendMessage(ChatUtil.translate("&7| &9IPs: &f" + args[5]));
        player.sendMessage(ChatUtil.translate("§7§m------------------------------"));
    }
}
